// import type { Metadata } from "next";
// import { Geist_Mono, Inter, Lora } from "next/font/google";
// import "./globals.css";
// import Script from "next/script";
// // import ThemeProvider from "./theme/ThemeProvider ";

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${inter.variable} ${geistMono.variable}  antialiased     bg-white dark:bg-[#232530] transition-colors duration-700 ease-in-out`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }




// import type { Metadata } from "next";
// import { Geist_Mono, Inter, Lora } from "next/font/google";
// import "./globals.css";
// import Script from "next/script";
// import { Providers } from "./theme/ThemeProvider ";
// // import ThemeProvider from "./theme/ThemeProvider ";

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         // className={`${inter.variable} ${geistMono.variable}  antialiased `}
//         className={`${inter.variable} ${geistMono.variable} ${lora.variable} antialiased     `}
//       >
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './theme/ThemeProvider ';
import ThemeSwitch from './component/__organism/themeSwitch/ThemeSwitch';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Your App Name',
  description: 'Your app description',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white dark:bg-dark`}>
        <Providers>
          <ThemeSwitch />
          {children}
        </Providers>
      </body>
    </html>
  );
}