// import type { Metadata } from "next";
// import { Geist_Mono, Inter, Lora } from "next/font/google";
// import "./globals.css";
// import { Providers } from "./theme/ThemeProvider ";
// import ThemeSwitch from "./component/__organism/themeSwitch/ThemeSwitch";


// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {


//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${inter.variable} ${geistMono.variable} ${lora.variable} antialiased`}
//       >
//         <Providers>
//           <ThemeSwitch /> 
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );

// }



import type { Metadata } from "next";
import { Geist_Mono, Inter, Lora } from "next/font/google";
import "./globals.css";
import { Providers } from "./theme/ThemeProvider ";
import ThemeSwitch from "./component/__organism/themeSwitch/ThemeSwitch";
import FontSwitch from "./component/__organism/fontSwitch/FontSwitch ";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${geistMono.variable} ${lora.variable} antialiased`}
      >
        <Providers>
          <ThemeSwitch /> 
          <FontSwitch />
          {children}
        </Providers>
      </body>
    </html>
  );

}
